{{- if .Values.ingress.ui.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "omni-v2.fullname" . }}-ui
  namespace: {{ include "omni-v2.namespace" . }}
  labels:
    {{- include "omni-v2.labels" . | nindent 4 }}
    {{- with .Values.ingress.ui.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.ingress.ui.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.ui.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.ui.tls }}
  tls:
    {{- toYaml .Values.ingress.ui.tls | nindent 4 }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.ui.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "omni-v2.fullname" $ }}
                port:
                  number: {{ .Values.service.main.omniPort }}
{{- end }}
