{{- if .Values.gatewayApi.kubernetesProxy.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.gatewayApi.kubernetesProxy.name }}
  namespace: {{ include "omni-v2.namespace" . }}
  labels:
    {{- include "omni-v2.labels" . | nindent 4 }}
    {{- with .Values.gatewayApi.kubernetesProxy.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.gatewayApi.kubernetesProxy.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.gatewayApi.kubernetesProxy.parentRefs | nindent 4 }}
  hostnames:
    {{- toYaml .Values.gatewayApi.kubernetesProxy.hostnames | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "omni-v2.fullname" $ }}
          port: {{ .Values.service.main.kubernetesProxyPort }}
{{- end }}