{{- if not .Values.etcdEncryptionKey.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omni-v2.fullname" . }}-etcd-key
  labels:
    {{- include "omni-v2.labels" . | nindent 4 }}
type: Opaque
stringData:
  # The key name in the secret will be "omni.asc"
  omni.asc: |
    {{- .Values.etcdEncryptionKey.data.omni.asc | nindent 4 }}
{{- end }}